name: 01_01_02_24_hello_world

on:
  push:
    branches:
      - main

env:
  TASK_FOLDER: "${{ github.workspace }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Pull Selenoid Chrome (latest available)
        run: |
          docker pull selenoid/vnc_chrome:139.0
          docker pull selenoid/video-recorder:latest-release

      - name: Start Selenoid
        run: |
          docker compose -f docker-compose up -d

      - name: Wait for container to start
        run: sleep 1

      - name: Wait Selenoid status
        run: curl http://127.0.0.1:4444/status

      - name: Build with Maven
        run: mvn -B test

      - name: Generate Surefire HTML report
        run: mvn surefire-report:report

      - name: Uploading report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./target/site/surefire-report.html

      - name: Uploading video
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: ./video

      - name: Uploading logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./logs
